services:
    db:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: area42_software
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    app:
        build: .
        restart: "no"
        ports:
            - "8000:8000"
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: area42_software
            DB_USERNAME: postgres
            DB_PASSWORD: secret
        depends_on:
            - db

volumes:
    pgdata:
